### ISSUE TITLE
DEMC synchronization

### ISSUE THREAD

**Issue by pcubillos** [pcubillos/MCcubed#10]
Is it possible to synchronize the DEMC chains iteration (wait on each iteration for all chains to be done) without using Pipe calls?
I tried with locks and such for a day, but I failed miserably ...

**Comment by natelust** [comment]
What problem have you been having with locks?

**Comment by pcubillos** [comment]
... I should have documented that better, it was over a month ago.
I don't remember the details but, I could never make to work a Lock that locks when the first chain finished the iteration, and then get released when the last chain finished.
I tried dozens of different variations, with Semaphores, Conditions, Locks, Events, shared-memory variables as flags, ... always something different failed.

There's probably a solution out there, I just couldn't figured it out.

**Comment by pcubillos** [comment]
Doesn't really worth it given the snooker algorithm.
