### ISSUE TITLE
Red noise with wavelet algorithm

### ISSUE THREAD

**Issue by huhell** [pcubillos/MCcubed#108]
I am trying to use the implemented wavelet algorithm to estimate the red noise in exoplanet light curves. So I give inputs for gamma, sigma_w and sigma_r, but I always get a negative calculated chi**2 (although it seems the mcmc runs normally), any idea ?

Thank you !

**Comment by huhell** [comment]
Actually it gives the -log(likelihood) that is why, my mistake.

**Comment by pcubillos** [comment]
Ahh, OK.  Sorry that I didn't answer earlier, I'm traveling these days.
