### ISSUE TITLE
DEMC with no syncronization? (multiproc branch)

### ISSUE THREAD

**Issue by pcubillos** [pcubillos/MCcubed#7]
Test what happens if we implement DEMC but without synchronizing at the end of each iteration.  This deviates from the original algorithm of ter Braak (2006). But still, check if the results looks ok.  This should be much faster than the current version of DEMC (the pipe's communications are a bottleneck).

**Comment by joeharr4** [comment]
Please check with Tom Loredo if this changes the algorithm in any way.

--jh--

Date: Mon, 22 Jun 2015 14:07:05 -0700

**Comment by natelust** [comment]
If you don't synchronize the chains, you can't get the history populated correctly. You need to write to and create the history so you can draw from the States of where you have been. That is exactly what the whole point of this algorithm is. If pipes are what is slowing the while thing down moving to a shared memory model with locks is the way to go. Is there a profile of the code somewhere running I can look at? Maybe you are more clever than I though, and you can see a way of doing this that I cannot. If you don't sync up, effectively you are just running one chain at a time...

**Comment by natelust** [comment]
Also is it the pipe communication time or the fact that it must wait until all the chains are done to move on to the next iteration?

**Comment by pcubillos** [comment]
I have the hunch that we both are not completely clear about what the other one is saying. The issue is not fully descriptive of my idea (and my idea is still not completely defined).  After all, this is just an experiment (and is labeled as such).

I do have an algorithm (still in my head, not in the repo) to write the history correctly with a minimal amount of communication (if it works).  The proposal jump is still taken from the diff of two other chains, it's just that each chain does not need to wait for the others to take the next step.

On your second question, Nate. I don't know which of the two has the largest impact in performance. But I do know that the pure existence of pipes sending and receiving data (as small the data-size being transferred can be) does has a noticeable impact on the timing.

**Comment by pcubillos** [comment]
Doesn't really worth it given the snooker algorithm.
